# 工作流程名称
name: Convert_Ruleset_JSON_to_SRS

# 触发条件
on:
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟运行一次
  workflow_dispatch:  # 允许手动触发

# 定义作业
jobs:
  update-and-convert:
    runs-on: windows-latest  # 使用 Windows 运行环境

    steps:
      # 步骤1：检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # 步骤2：下载并解压 sing-box 到根目录
      - name: Download and extract sing-box
        run: |
          $url = "https://github.com/SagerNet/sing-box/releases/download/v1.9.4/sing-box-1.9.4-windows-amd64.zip"
          $zipFile = "sing-box.zip"
          $extractPath = "${{ github.workspace }}"  # 将文件解压到根目录

          # 下载并解压 sing-box
          Invoke-WebRequest -Uri $url -OutFile $zipFile
          Expand-Archive -Path $zipFile -DestinationPath $extractPath -Force
          Remove-Item -Path $zipFile

      # 步骤3：使用 sing-box 转换规则集
      - name: Convert ruleset using sing-box
        run: |
          $exePath = "${{ github.workspace }}\sing-box-1.9.4-windows-amd64\sing-box.exe"
          
          & $exePath rule-set compile --output adblock_reject_domain.srs adblock_reject_domain.json

      # 步骤4：提交并推送更改
      - name: Push changes
        shell: bash
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add adblock_reject_domain.srs
          git commit -m "Update adblock_reject_domain.srs"
          git push https://${{ secrets.TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }} --force
